server:
  port: 9090

tomato-rpc:
  # 微服务id
  micro-service-id: "demo-rpc-service"
  subscribed-services:
    - "demo-downstream-rpc-service"
  # 注册中心地址
  name-service-uri: "127.0.0.1:2181"
  # RPC服务暴露的端口
  port: 4567
  # RPC服务处理线程池数量
  business-thread: 100
  # 服务环境
  stage: "dev"
  # 服务分组
  group: "main"
  # 服务端空闲连接检测时间间隔，单位ms
  server-idle-check-ms: 600000
  # 客户端发送心跳包的时间间隔，单位ms
  client-keep-alive-ms: 200000